# Workflow file to push Verademo API to Amazon ECR

name: Push the Docker image to AWS ECR Repo
on:
  workflow_dispatch:
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push the image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: vuln_images
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t verademo-api .
          docker tag verademo-api $REGISTRY/$REPOSITORY:verademo-api-latest
          docker tag verademo-api $REGISTRY/$REPOSITORY:verademo-api-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:verademo-api-latest
          docker push $REGISTRY/$REPOSITORY:verademo-api-$IMAGE_TAG