# This file contains the essential steps for getting the app packaged and scanned using Veracode's various
# scan types.  We suggest starting with the elements in this file and fully understanding them before
# attempting more advanced use cases, like 'Pipeline scan on a PR', or importing Issues.

# The essential steps shown below are:
#   checkout and package the app for scanning
#   upload for a static scan
#   run the SCA agent scan
#   run the Container scan

name: the-essentials

on:
  workflow_dispatch:
    
jobs:
  checkout-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
    
      - name: Zip Application Files 
        run: |
          sudo apt-get install zip
          zip -r verademo-api.zip .

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-target
          path: verademo-api.zip

  upload-scan:
    needs: checkout-and-package
    runs-on: ubuntu-latest
    container:
      image: veracode/api-wrapper-java:latest
      options: --user root

    steps:
      - name: get artifact
        uses: actions/download-artifact@v4
        with:
          name: scan-target

      # debugging steps can be handy...
      - name: debug1
        run: |
          pwd
          ls -l

      - name: scan
        run: |
          java -jar /opt/veracode/api-wrapper.jar \
            -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} \
            -action UploadAndScan -appname "Verademo-API" -createprofile true \
            -filepath verademo-api.zip -version "GitHub $GITHUB_RUN_NUMBER"
        continue-on-error: true

# the above steps are the bare minimum.
# below are some additional steps that are commonplace
  sca-scan:
    needs: checkout-and-package     # OK not really, but keeps things cleaner
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: debug1
        run: |
          pwd
          ls -l

      - name: do SCA scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.12
        with:
          path: ./
          create-issues: false
          
      - name: display SCA results
        run: |
          cat scaResults.txt

  container-scan:
    needs: checkout-and-package     # OK not really, but keeps things cleaner
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: do container scan
        uses: veracode/container_iac_secrets_scanning@v1.0.0
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "table"