name: Veracode IaC Scan

permissions:
  contents: read
  security-events: write
  actions: read
  issues: write

on:
  push:
    branches:
      - feature/*

jobs:
    Veracode-container_iac_secrets-scan:
        runs-on: ubuntu-latest
        name: Veracode Container/IaC/Secrets scan

        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Veracode Container/IaC/Secrets action step
          uses: veracode/container_iac_secrets_scanning@v1.0.1
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: false
            fail_build: true